// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfSqlite_v2.Models;

#nullable disable

namespace WpfSqlite_v2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230310105959_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("WpfSqlite_v2.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "RPG",
                            Price = 34.89m,
                            Title = "Wiedźmin"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "RPG",
                            Price = 34.89m,
                            Title = "Wiedźmin 2"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "FPS",
                            Price = 34.89m,
                            Title = "GTA V"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "RPG",
                            Price = 34.89m,
                            Title = "Diablo III"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "RPG",
                            Price = 34.89m,
                            Title = "Diablo IV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
