// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormWithSqLite.Data;

#nullable disable

namespace WinFormWithSqLite.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    partial class MyAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("WinFormWithSqLite.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Nabiał"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Słodycze"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "AGD"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Napoje"
                        });
                });

            modelBuilder.Entity("WinFormWithSqLite.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Ser tłusty"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Name = "Ser chudy"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Name = "Ser żółty"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Name = "krówki polskie"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Name = "Czekolada mleczna"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Name = "Landrynki małe"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Name = "Proszek do ...."
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Name = "Płyn do płukania"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Name = "Papier toaletowy"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Name = "Coca-Cola"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Name = "Pepsi-Cola"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            Name = "Mirinda"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            Name = "Oranżada polska"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Name = "Napój gazowany"
                        });
                });

            modelBuilder.Entity("WinFormWithSqLite.Models.Product", b =>
                {
                    b.HasOne("WinFormWithSqLite.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WinFormWithSqLite.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
